// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tracerMapEvents                 = "events"
	tracerMapRecvSockMap            = "recv_sock_map"
	tracerMapSockMap                = "sock_map"
	tracerProgHandleExec            = "handle_exec"
	tracerProgHandleTcpConnectEntry = "handle_tcp_connect_entry"
	tracerProgHandleTcpConnectExit  = "handle_tcp_connect_exit"
	tracerProgHandleTcpRecvmsgEntry = "handle_tcp_recvmsg_entry"
	tracerProgHandleTcpRecvmsgExit  = "handle_tcp_recvmsg_exit"
	tracerProgHandleTcpSendmsg      = "handle_tcp_sendmsg"
)

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	HandleExec            *ebpf.ProgramSpec `ebpf:"handle_exec"`
	HandleTcpConnectEntry *ebpf.ProgramSpec `ebpf:"handle_tcp_connect_entry"`
	HandleTcpConnectExit  *ebpf.ProgramSpec `ebpf:"handle_tcp_connect_exit"`
	HandleTcpRecvmsgEntry *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_entry"`
	HandleTcpRecvmsgExit  *ebpf.ProgramSpec `ebpf:"handle_tcp_recvmsg_exit"`
	HandleTcpSendmsg      *ebpf.ProgramSpec `ebpf:"handle_tcp_sendmsg"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	Events      *ebpf.MapSpec `ebpf:"events"`
	RecvSockMap *ebpf.MapSpec `ebpf:"recv_sock_map"`
	SockMap     *ebpf.MapSpec `ebpf:"sock_map"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	Events      *ebpf.Map `ebpf:"events"`
	RecvSockMap *ebpf.Map `ebpf:"recv_sock_map"`
	SockMap     *ebpf.Map `ebpf:"sock_map"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.Events,
		m.RecvSockMap,
		m.SockMap,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	HandleExec            *ebpf.Program `ebpf:"handle_exec"`
	HandleTcpConnectEntry *ebpf.Program `ebpf:"handle_tcp_connect_entry"`
	HandleTcpConnectExit  *ebpf.Program `ebpf:"handle_tcp_connect_exit"`
	HandleTcpRecvmsgEntry *ebpf.Program `ebpf:"handle_tcp_recvmsg_entry"`
	HandleTcpRecvmsgExit  *ebpf.Program `ebpf:"handle_tcp_recvmsg_exit"`
	HandleTcpSendmsg      *ebpf.Program `ebpf:"handle_tcp_sendmsg"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.HandleExec,
		p.HandleTcpConnectEntry,
		p.HandleTcpConnectExit,
		p.HandleTcpRecvmsgEntry,
		p.HandleTcpRecvmsgExit,
		p.HandleTcpSendmsg,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_x86_bpfel.o
var _TracerBytes []byte
